-- 사용자(회원) 정보를 저장할 테이블
CREATE TABLE USER_INFO(
	ID VARCHAR2(100) CONSTRAINT USER_INFO_ID_PK PRIMARY KEY,
	PWD VARCHAR2(100) CONSTRAINT USER_INFO_PWD_NN NOT NULL,
	EMAIL VARCHAR2(100),
	PROFILE VARCHAR2(100), --프로필 이미지 경로를 저장할 칼럼
	REGDATE DATE -- 가입일
);

-- 업로드된 파일의 정보를 저장할 테이블
CREATE TABLE board_file(
	NUM NUMBER PRIMARY KEY,
	WRITER VARCHAR2(100) NOT NULL,
	TITLE VARCHAR2(100) NOT NULL,
	ORGFILENAME VARCHAR2(100) NOT NULL, -- 원본 파일명
	SAVEFILENAME VARCHAR2(100) NOT NULL, -- 서버에 실제로 저장된 파일명
	FILESIZE NUMBER NOT NULL, --파일의 크기
	REGDATE DATE
);

CREATE SEQUENCE board_file_seq;